Dots/Dots.xcodeproj/project.pbxproj, Dots/Dots.xcodeproj/project.xcworkspace/contents.xcworkspacedata, Dots/Dots.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, Dots/Dots/Assets.xcassets/AccentColor.colorset/Contents.json, Dots/Dots/Assets.xcassets/AppIcon.appiconset/Contents.json, Dots/Dots/Assets.xcassets/Contents.json, Dots/Dots/Dots.xcdatamodeld/.xccurrentversion, Dots/Dots/Dots.xcdatamodeld/Dots.xcdatamodel/contents, Dots/Dots/DotsApp.swift, Dots/Dots/Info.plist, Dots/Dots/Persistence.swift, Dots/Dots/Preview Content/Preview Assets.xcassets/Contents.json, Dots/Dots/View/MainView.swift
- [ x ] 파일 및 폴더 수정/삭제
- [ x ] Merge 하는 브랜치가 올바른가?
- [ x ] 변경 사항의 동작을 확인하였는가?
=> [Setting] Project Foldering(#3)

Dots/Dots.xcodeproj/project.pbxproj, Dots/Dots/Model/Ex+DotsModel_Create.swift
=> [FIX] EX+DotsModel_Create 추적 오류 해결

Dots/Dots.xcodeproj/project.pbxproj, Dots/Dots/View/ContactView/addContactsView.swift, Dots/Dots/View/ContactView/contactsJobCompany.swift, Dots/Dots/View/ContactView/contactsMemo.swift, Dots/Dots/View/ContactView/contactsStrength.swift
#5 인맥 추가, 디테일
직업, 회사, 강점 모달을 제외한 뷰는 완성
=> Feat/5 contacts add detail UI

Dots/Dots/View/ContactView/addContactsView.swift, Dots/Dots/View/ContactView/contactsJobCompany.swift, Dots/Dots/View/ContactView/contactsStrength.swift
#5 인맥추가, 디테일
직업, 회사, 강점 뷰에서 임시로 Text입력이 보이도록 수정하였습니다.
=> [CHORE] : 회사, 직무, 강점에서 임시로 text가 보이도록 변경

Dots/Dots/View/Component/StrengthList.swift, Dots/Dots/View/Modals/AddStrengthModal.swift, Dots/Dots/View/Modals/SelectLevelModal.swift, Dots/Dots/View/SearchConnectionView.swift
=> [CHORE] 코드 컨벤션 맞추기 #22

Dots/Dots/Model/Ex+DotsModel_Create.swift, Dots/Dots/View/SearchConnectionView.swift
- Resolved: #26 
인맥 삭제 기능 구현
nil
=> [FEAT] 인맥 삭제 기능 구현

Dots/Dots/Model/DotsModel.swift, Dots/Dots/Model/Ex+DotsModel_Create.swift, Dots/Dots/View/Component/CustomDetailList.swift, Dots/Dots/View/Modals/StrengthNoteModal.swift, Dots/Dots/View/MyStrengthDetailView.swift, Dots/Dots/View/MyStrengthView.swift
- Resolved: #35 
- 내 강점 디테일 뷰와 CoreData 연동
- 내 강점 노트 CoreData 연동
nil
=> [FEAT] 노트 저장, 디테일뷰 CoreData 연동

Dots/Dots/Model/Ex+DotsModel_Create.swift, Dots/Dots/View/Modals/AddStrengthModal.swift
- Resolved: #44 
강점 추가 시 중복 검사 로직을 수정하였습니다.
nil
=> [FEAT] 나의 강점 추가 기능 로직 수정

Dots/Dots/Model/Ex+DotsModel_Create.swift, Dots/Dots/View/ContactView/addContactsView.swift, Dots/Dots/View/ContactView/contactsImageSelect.swift, Dots/Dots/View/ContactView/contactsUserProfile.swift
- Resolved: #49 
인맥 추가 기능을 구현하였습니다.
- 강점 추가 기능을 추가로 구현하여야 함.
=> [FEAT] 인맥 추가 기능 연동

Dots/Dots/View/Component/CustomConnectionList.swift, Dots/Dots/View/ConnectionDetailView.swift, Dots/Dots/View/Modals/ConnectionProfileModal.swift, Dots/Dots/View/SearchConnectionView.swift
- Resolved: #51
인맥 상세 뷰에 CoreData와 연동하여 동적으로 데이터를 읽어옵니다!
=> [FEAT] 인맥 상세 뷰 데이터 연동

Dots/Dots.xcodeproj/project.pbxproj, Dots/Dots/View/ContactView/ContactsSelectListView.swift, Dots/Dots/View/SearchConnectionView.swift
=> Feat/55 contacts select list view UI

Dots/Dots.xcodeproj/project.pbxproj, Dots/Dots/Extensions/Ex+MyStrengthNoteEntity.swift, Dots/Dots/Extensions/Ex+NetworkingPersonEntity.swift, Dots/Dots/Model/DotsModel.swift, Dots/Dots/Model/Ex+DotsModel_Create.swift, Dots/Dots/View/Component/CustomConnectionList.swift, Dots/Dots/View/Modals/ConnectionProfileModal.swift, Dots/Dots/View/SearchConnectionView.swift
- Resolved: #58
커스텀 리스트를 조금 더 자연스럽게 바꾸었습니다.
=> [FEAT] 인맥 Delete기능 구현

Dots/Dots/View/SearchConnectionView.swift
=> [FIX] Merge Conflict 수정

Dots/Dots/Model/Ex+DotsModel_Create.swift, Dots/Dots/View/Modals/StrengthNoteModal.swift, Dots/Dots/View/MyStrengthDetailView.swift
- Resolved: #62 
강점별 노트를 확인할 수 있습니다.
강점별로 노트를 생성할 수 있습니다.
=> [FEAT] 강점별 노트 구현

Dots/Dots/View/ContactView/addContactsView.swift
=> [CHOER] : 버그 수정

Dots/Dots/View/ContactView/addContactsView.swift
#5 인맥 추가 디테일
연락처에서 정보를 가져오는 fetch 함수 작성
=> [FEAT] : 연락처에서 상세정보를 가져오는 fetch문 완성

Dots/Dots.xcodeproj/project.pbxproj, Dots/Dots/Extensions/RounededCorner.swift, Dots/Dots/View/Modals/AddStrengthModal.swift, Dots/Dots/View/MyStrengthView.swift
이미 존재하는 강점 검색시 첫글자만 검색이 아니라 모든 글자 검색이 가능합니다
stroke가 제대로 보이지 않는 문제 수정
버튼 클릭시 스트로크를 넘어서 색칠되는 문제 수정
=> Feat/70 add strength modal UI

Dots/Dots.xcodeproj/project.pbxproj, Dots/Dots/View/SearchConnectionView.swift, Dots/Dots/View/SearchView/SearchFilterDetailView.swift, Dots/Dots/View/SearchView/SearchFilterListRow.swift, Dots/Dots/View/SearchView/SearchFilterView.swift
=> [FEAT] 검색 기능 일부 구현

Dots/Dots/View/Modals/ConnectionNoteModal.swift
=> [CHORE] 인맥 노트 모달 캘린더 변수 추가

Dots/Dots/Model/Ex+DotsModel_Create.swift, Dots/Dots/View/ContactView/ContactsSelectListView.swift, Dots/Dots/View/ContactView/addContactsView.swift, Dots/Dots/View/ContactView/contactsJobCompany.swift
#58 인맥 커스텀 뷰
Coredata 버그 수정, 모달이 닫히게 변경
=> [CHORE] : CoreData 버그 수정, 모달이 닫히도록 수정

Dots/Dots/View/ContactView/ContactsSelectListView.swift, Dots/Dots/View/ContactView/addContactsView.swift, Dots/Dots/View/SearchConnectionView.swift
#58 인맥 커스텀 뷰완료
저장이 완료되면 연락처 페이지로 돌아옵니다.
=> [FEAT] :  저장이 완료되면 연락처로 되돌아 옵니다.

Dots/Dots/Model/Ex+DotsModel_Create.swift, Dots/Dots/View/Component/CustomDetailList.swift, Dots/Dots/View/Component/SwipeItemView.swift, Dots/Dots/View/Modals/ConnectionNoteModal.swift, Dots/Dots/View/MyStrengthDetailView.swift
Close #75 
강점 디테일 리스트 스와이프 삭제 기능
=> [FEAT] 강점 디테일 리스트 스와이프 삭제 기능

Dots/Dots/View/ContactView/contactsJobCompany.swift
#91 
균규니의 회사,직무 모달 연동 -> 기능이 작동하지는 않음
=> [FEAT]: 회사, 직무 모달 연결 -> 기능이 작동하지는 않음

Dots/Dots/DotsApp.swift
Close #96 
- 앱 전체 Alert 컬러 systemBlue로 수정
=> [FIX] Alert 컬러 고정 #96

Dots/Dots/View/Component/CustomDetailList.swift, Dots/Dots/View/Component/CustomList.swift, Dots/Dots/View/Component/SwipeItemView.swift, Dots/Dots/View/SearchConnectionView.swift
Close #100 
(강점 디테일 리스트에만 적용)
- 떠있을때 탭 -> 삭제 뷰 닫기
- 안 떠있을때 탭 -> 열기
=> [FIX] 스와이프 삭제 취소 인터랙션

Dots/Dots.xcodeproj/project.pbxproj, Dots/Dots/View/ContactView/addContactsView.swift, Dots/Dots/View/ContactView/contactsJobCompany.swift, Dots/Dots/View/SearchConnectionView.swift, Dots/Dots/View/SearchView/SearchFilterDetailView.swift, Dots/Dots/View/SearchView/SearchFilterListRow.swift, Dots/Dots/View/SearchView/SearchFilterView.swift
=> [FEAT] 앤디 코드 합치기(#76)

Dots/Dots/View/ContactView/contactsJobCompany.swift, Dots/Dots/View/Modals/AddStrengthModal.swift, Dots/Dots/View/SearchConnectionView.swift, Dots/Dots/View/SearchView/SearchFilterDetailView.swift, Dots/Dots/View/SearchView/SearchFilterListRow.swift, Dots/Dots/View/SearchView/SearchFilterView.swift
강점이 추가됐을때 StrengthName이 초기화 되는 오류 해결
=> [FIX] 강점 추가 오류 해결(#76)

Dots/Dots/View/ConnectionView/ConnectionAddStrength.swift, Dots/Dots/View/ConnectionView/ConnectionDetailView.swift, Dots/Dots/View/ConnectionView/ConnectionNoteList.swift
=> [FEAT] 인맥 디테일뷰 강점 비교 구현(임시)

Dots/Dots/View/ContactView/addContactsView.swift, Dots/Dots/View/ContactView/contactsJobCompany.swift
=> [CHORE] 고정값 입력 유티용 (#112)

Dots/Dots/View/Component/StrengthList.swift, Dots/Dots/View/ConnectionView/ConnectionAddStrength.swift, Dots/Dots/View/Modals/AddStrengthModal.swift
미입력 시 x버튼 제거
직접 추가하기 태그화
이미 존재하는 강점 선택 시 키보드 Hide 및 강점 태그화
강점 리스트 테두리(Stroke) 수정
=> Feat/125 add strength modal UI

Dots/Dots.xcodeproj/project.pbxproj, Dots/Dots/Model/Ex+DotsModel_Create.swift, Dots/Dots/View/ContactView/addContactsView.swift, Dots/Dots/View/ContactView/contactsJobCompany.swift, Dots/Dots/View/ContactView/contactsStrength.swift, Dots/Dots/View/ContactView/contactsTextField.swift
=> [FIX] 인맥관리 강점 추가 기능

Dots/Dots/Model/Ex+DotsModel_Create.swift, Dots/Dots/View/ContactView/addContactsView.swift, Dots/Dots/View/SearchConnectionView.swift
=> [FIX] Resolved hot fix error

Dots/Dots/Model/Ex+DotsModel_Create.swift, Dots/Dots/View/ConnectionView/ConnectionDetailView.swift, Dots/Dots/View/ConnectionView/ConnectionNoteList.swift
- close #77
- 인맥 프로필에서 회사, 직무 폰트 및 색상 변경
- 인맥 기록(노트) 스와이프 삭제 기능 구현
=> [FEAT] 인맥 노트 삭제 기능 구현

Dots/Dots/View/SearchView/SearchFilterView/SearchFilterDetailView.swift
직무 필터링 검색시 최근검색 기능이 누락되어서 추가했습니다.
=> [BUG] 직무 부분 최근검색 기록 누락 해결 (#134)

Dots/Dots.xcodeproj/project.pbxproj, Dots/Dots/Model/StrengthLevelImage.swift, Dots/Dots/View/MyStrengthView/Visualization/MetaballAnimation.swift, Dots/Dots/View/MyStrengthView/Visualization/PathCircle.swift, Dots/Dots/View/SearchView/Modal/ContactsListRow.swift
- Resolved: #139 
메타볼 뿌셔버렸습니다.
https://github.com/DeveloperAcademy-POSTECH/MC3-Team3-GrayMa/assets/77708819/93f76899-37d1-4012-9ea3-e67da254e4b5
참고 문헌 : https://swiftwithmajid.com/2022/05/18/mastering-timelineview-in-swiftui/
=> [FEAT] Meta ball 구현

Dots/Dots/View/Component/CustomConnectionList.swift, Dots/Dots/View/SearchView/Modal/ContactsListRow.swift, Dots/Dots/View/SearchView/SearchConnectionView.swift
- Resolved: #149 
- 인맥 랜덤 삭제되는 것 수정
- 인맥 프로필 변경시 목록에서도 적용
=> [FIX] SearchView 오류 수정

Dots/Dots/View/SearchView/SearchFilterView/SearchFilterListRow.swift, Dots/Dots/View/SearchView/SearchFilterView/SearchFilterView.swift
필터 선택시 삭제 버튼 안눌리는 이슈 해결 필터 하이라이트 색 변경
=> [FEAT] 필터 선택시 삭제 버튼 안눌리는 이슈 해결 하이라이트 색 변경(#159)

Dots/Dots/View/ContactView/ContactsSelectListView.swift
=> [CHORE] : UI 디자인 변경

Dots/Dots.xcodeproj/project.pbxproj, Dots/Dots/View/ContactView/ContactsStrengthField.swift, Dots/Dots/View/ContactView/Modal/AddStrengthSheet.swift
- Related: #158 
인맥관리 강점 추가 모달 구현
=> [FEAT] 인맥관리 강점 추가 모달 구현

Dots/Dots/View/MyStrengthView/MyStrengthView.swift
=> [FEAT] 메타볼 3개로 제한, 강점 레벨 순 + 메모 개수 순

Dots/Dots/View/MyStrengthView/Components/CustomList.swift, Dots/Dots/View/MyStrengthView/MyStrengthView.swift
=> Feat/170 mystrength view UI

Dots/Dots/View/MyStrengthDetailView/Components/PortraitBtn.swift, Dots/Dots/View/MyStrengthDetailView/MyStrengthDetailView.swift
Close #179 
- Portrait 버튼 UI 변경
- 버튼 페이지 이동
=> [FEAT] 강점 디테일 Portrait 버튼 이동 기능

Dots/Dots/Modifier/TextModifier.swift, Dots/Dots/View/Component/CustomConnectionList.swift, Dots/Dots/View/SearchView/SearchFilterView/SearchFilterListRow.swift
강점 하이라이트가 글씨 크기에 맞춰서 변합니다
회사와 직무가 너무 길때 글자가 짤려보이는 오류 수정
=> Feat/178 custom connection list UI

Dots/Dots/View/Component/CustomConnectionList.swift, Dots/Dots/View/ConnectionView/ConnectionDetailView.swift, Dots/Dots/View/ContactView/contactsImageSelect.swift, Dots/Dots/View/ContactView/contactsUserProfile.swift, Dots/Dots/View/MyStrengthDetailView/Components/PortraitBtn.swift
Close #188 
User Image 들어가는 모든 뷰 배경색 설정
- ConnectionDetailView
- contactsUserProfile
- ContactsImageSelect
- CustomConnectionList
=> [ADD] UserImage 배경색 설정

Dots/Dots.xcodeproj/project.pbxproj, Dots/Dots/Info.plist, Dots/Dots/View/ContactView/ContactsUserProfile.swift, Dots/Dots/View/ContactView/contactsImageSelect.swift
[FEAT] : Quick action 추가
퀵 액선 추가, 오타 수정
=> [CHORE] : 오타 수정

Dots/Dots/Model/Ex+DotsModel_Create.swift, Dots/Dots/View/ContactView/Modal/AddStrengthSheet.swift, Dots/Dots/View/ContactView/addContactsView.swift
인맥을 새로 등록할 때 강점 목록을 DB에 연동하였습니다
=> [FEAT] 인맥 등록시 강점 추가 DB 연결

Dots/Dots/View/Component/CustomConnectionList.swift
=> [FIX] 불릿 오류 수정(#195)

Dots/Dots/View/ConnectionView/ConnectionDetailView.swift, Dots/Dots/View/ConnectionView/ConnectionProfileEditView.swift
close #192 
인맥 개인에 대한 프로필을 변경할 때 최초 등록과 동일한 UI와 제약사항을 적용했습니다.
=> [FEAT] 인맥 프로필 수정 UI 적용

Dots/Dots/View/ConnectionView/ConnectionDetailView.swift
close #199
인맥 프로필뷰에서 스크롤 시 배경 색상이 잘려보이는 부분을 수정했습니다.
=> [FIX] Sticky Header 배경 수정

Dots/Dots/View/Component/CustomConnectionList.swift, Dots/Dots/View/ContactView/addContactsView.swift
강점이 너무 길때 트렁캣 처리로 변경 이미지가 없을때 기본 이미지로 변경 (#195)
이미지 등록이 안됐을때 기본이미지로 변경
=> [fix] 강점이 너무 길때 트렁캣 처리로 변경 이미지가 없을때 기본 이미지로 변경 (#195)

Dots/Dots/View/MyStrengthView/Components/CustomList.swift
=> [fix] 커스텀리스트 ui수정(#202)

Dots/Dots/View/ContactView/ContactsEmailField.swift, Dots/Dots/View/ContactView/Modal/AddStrengthSheet.swift
#202 
email 수정시 색상이 잘못 나오던 버그 수정
강점 추가시 키보드 return하면 삭제가 안되던 버그 수정
=> Bug/202 mainstrength UI

Dots/Dots/Info.plist
=> [DEl] : 빠른 인맥 추가 삭제

Dots/Dots/View/ConnectionView/ConnectionDetailView.swift, Dots/Dots/View/MyStrengthDetailView/Components/PortraitBtn.swift, Dots/Dots/View/MyStrengthDetailView/MyStrengthDetailView.swift
Close #211 
강점디테일 -> 인맥 상세 페이지 '뒤로가기' 텍스트 변경
=> [FIX] 강점디테일>인맥 버튼 텍스트 변경

Dots/Dots.xcodeproj/project.pbxproj, Dots/Dots/AppDelegate.swift, Dots/Dots/DotsApp.swift, Dots/Dots/Info.plist, Dots/Dots/Model/Action.swift, Dots/Dots/View/MainView.swift, Dots/Dots/View/MyStrengthView/MyStrengthView.swift, Dots/Dots/View/SearchView/SearchConnectionView.swift
Relate #213 
- 연락처부터 인맥 추가
- 새로 인맥 추가
=> [FEAT] 퀵액션 기능 구현 완료

Dots/Dots/View/MyStrengthView/MyStrengthView.swift, Dots/Dots/View/MyStrengthView/Visualization/MetaballAnimation.swift
=> [FEAT] Metaball 인터랙션 구현

Dots/Dots/View/MyStrengthView/MyStrengthView.swift
Close #204 
###Metaball 인터랙션
- 인터랙션 애니메이션 : Xcode 14용으로 변경
- 터치 인식 범위 조정
- 햅틱 피드백
=> [FEAT] Metaball 인터랙션 - 햅틱피드백

Dots/Dots/View/ContactView/ContactsEmailField.swift
Close #219 
- 인맥추가의 이메일 텍스트 컬러 자동 전환되는것 수정
=> [FIX] Email 텍스트필드 컬러 수정

Dots/Dots/View/ContactView/ContactsSelectListView.swift
=> [CHORE] : 기존 연락처 추가할때 검색어가 포함된 모든 정보를 가져옵니다.

README.md
=> Update README.md 초안

README.md
=> docs/add readme.md(#231)

README.md
=> 개인정보 처리방침 Update
